"""empty message

Revision ID: 35b264e89515
Revises: dedb76135242
Create Date: 2022-07-13 17:42:00.217295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35b264e89515'
down_revision = 'dedb76135242'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('api_key', sa.String(length=128), nullable=True))
    op.drop_column('user', 'API_KEY')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('API_KEY', sa.VARCHAR(), nullable=True))
    op.drop_column('user', 'api_key')
    op.drop_column('portfolio', 'user_id')
    # ### end Alembic commands ###
