"""add figi in model

Revision ID: 5662b3812a74
Revises: abffd46bb41b
Create Date: 2022-07-12 16:32:08.385026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5662b3812a74'
down_revision = 'abffd46bb41b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('position', sa.Column('figi', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('position', 'figi')
    # ### end Alembic commands ###
