"""add email to user

Revision ID: 617ba0b68456
Revises: f663bb25c810
Create Date: 2022-07-06 12:34:41.138805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '617ba0b68456'
down_revision = 'f663bb25c810'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
