"""rm lots from Position

Revision ID: 7c2b641cbb6a
Revises: 1000d75dc26a
Create Date: 2022-07-07 10:20:05.432063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c2b641cbb6a'
down_revision = '1000d75dc26a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('position', 'lots')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('position', sa.Column('lots', sa.FLOAT(), nullable=False))
    # ### end Alembic commands ###
