"""added "sector" in Position

Revision ID: 828c7ba5a6c4
Revises: 02bce31e66da
Create Date: 2022-07-01 10:33:51.305605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '828c7ba5a6c4'
down_revision = '02bce31e66da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('position', sa.Column('sector', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('position', 'sector')
    # ### end Alembic commands ###
