"""

Revision ID: b0459d7f5f4d
Revises: f1dc57ac3907
Create Date: 2022-07-13 15:45:14.938199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0459d7f5f4d'
down_revision = 'f1dc57ac3907'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio', sa.Column('user_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolio', 'user_id')
    # ### end Alembic commands ###
