"""

Revision ID: f1dc57ac3907
Revises: 99c4ec84468a
Create Date: 2022-07-13 15:37:56.037401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1dc57ac3907'
down_revision = '99c4ec84468a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolio', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio', sa.Column('user_id', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###
