"""removed "sector" in Position & added it in Instrument

Revision ID: f663bb25c810
Revises: 828c7ba5a6c4
Create Date: 2022-07-01 10:37:17.489226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f663bb25c810'
down_revision = '828c7ba5a6c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instrument', sa.Column('sector', sa.String(length=30), nullable=True))
    op.drop_column('position', 'sector')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('position', sa.Column('sector', sa.VARCHAR(length=30), nullable=True))
    op.drop_column('instrument', 'sector')
    # ### end Alembic commands ###
